#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 11) buffer PredictedPositions { vec4 predictedPos[]; };
layout(std430, binding = 13) buffer DeltaPositions { vec4 deltaPosBuf[]; };


uniform uint particleCount;
uniform vec3 boxMin;
uniform vec3 boxMax;
uniform float particleRadius;
uniform float pbfRelaxation;

void main() {
	uint idx = gl_GlobalInvocationID.x;
	if(idx >= particleCount) return;

	vec3 Pi = predictedPos[idx].xyz + pbfRelaxation * deltaPosBuf[idx].xyz;

	vec3 minB = boxMin + vec3(particleRadius);
	vec3 maxB = boxMax - vec3(particleRadius);
	Pi = clamp(Pi, minB, maxB);

	predictedPos[idx] = vec4(Pi, 1.0);

}
