#version 430 core 


layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 2) buffer CellCount { uint countBuf[]; };
layout(std430, binding = 3) buffer CellOffset { uint cellOffsetBuf[]; };
layout(std430, binding = 5) buffer ParticleCell { uint particleCell[]; };
layout(std430, binding = 6) buffer SortedIndex { uint sortedIndexBuf[]; };
layout(std430, binding = 11) buffer PredictedPositions { vec4 predictedPos[]; };
layout(std430, binding = 12) buffer Lambdas { float lambdaBuf[]; };
layout(std430, binding = 13) buffer DeltaPositions { vec4 deltaPosBuf[]; };
//layout(std430, binding = 8) readonly buffer BoundaryCellCount { uint boundaryCountBuf[]; };
//layout(std430, binding = 9) readonly buffer BoundaryCellStart { uint boundaryStartBuf[]; };
//layout(std430, binding = 10) readonly buffer BoundarySortedIndex { uint boundarySortedIndexBuf[]; };
//layout(std430, binding = 15) readonly buffer BoundaryPos { vec4 boundaryGhostPart[]; };
//

uniform uint particleCount;
uniform uint gridResX;
uniform uint gridResY;
uniform uint gridResZ;

uniform float h;
uniform float mass;
uniform float PI;
uniform float restDensity;

uniform float scorrK;
uniform float scorrN;
uniform float scorrDQ;

uint flatten(uvec3 c) {
	return c.x + gridResX * (c.y + gridResY * c.z);
}

float W_Poly6(float r, float hVal) {
	if(r >= hVal) return 0.0;
	float hr2 = hVal * hVal - r * r;
	float sigma = 315.0 / (64.0 * PI * pow(hVal, 9));
	return sigma * hr2 * hr2 * hr2;

}

vec3 gradW_spiky(vec3 Rij, float r, float hVal) {
	if(r <= 1e-6 || r >= hVal) return vec3(0.0);
	float coeff = -45.0 / (PI * pow(hVal, 6.0));
	float a = (hVal - r);
	return coeff * a * a * (Rij / r);
}


void main() {
	uint idx = gl_GlobalInvocationID.x;
	if(idx >= particleCount) return;

	vec3 Pi = predictedPos[idx].xyz;
	float Lambdai = lambdaBuf[idx];
	uint cellId = particleCell[idx];

	ivec3 base = ivec3(int(cellId % gridResX), int((cellId / (gridResX) % gridResY)), int(cellId / (gridResX * gridResY)));

	float dq = max(1e-6, scorrDQ * h);
	float wDQ = max(W_Poly6(dq, h), 1e-6);

	vec3 deltaFluid = vec3(0.0);
	vec3 deltaBoundary = vec3(0.0);

	for(int dz = -1; dz <= 1; dz++) {
		for(int dy = -1; dy <= 1; dy++) {
			for(int dx = -1; dx <= 1; dx++) {
				ivec3 c = base + ivec3(dx, dy, dz);
				if(c.x < 0 || c.y < 0 || c.z < 0) continue;
				if(c.x >= int(gridResX) || c.y >= int(gridResY) || c.z >= int(gridResZ)) continue;

				uint nCell = flatten(c);
				uint start = cellOffsetBuf[nCell];
				uint count = countBuf[nCell];

				for(uint i = 0u; i < count; i++) {
					uint j = sortedIndexBuf[start + i];
					if(j == idx) continue;

					vec3 Pij = Pi - predictedPos[j].xyz;
					float r = length(Pij);
					if(r >= h || r <= 1e-6) continue;

					float Lambdaj = lambdaBuf[j];
					float w = W_Poly6(r, h);
					float scorr = -scorrK * pow(w / wDQ, scorrN);

					vec3 gradW = gradW_spiky(Pij, r, h);
					deltaFluid += (Lambdai + Lambdaj + scorr) * gradW;



				}


			}


		}


	}
//	for(int dz = -1; dz <= 1; dz++) {
//		for(int dy = -1; dy <= 1; dy++) {
//			for(int dx = -1; dx <= 1; dx++) {
//				ivec3 c = base + ivec3(dx, dy, dz);
//				if(c.x < 0 || c.y < 0 || c.z < 0) continue;
//				if(c.x < 0 || c.y < 0 || c.z < 0) continue;
//				if(c.x >= int(gridResX) || c.y >= int(gridResY) || c.z >= int(gridResZ)) continue;
//
//				uint nCell = flatten(c);
//				uint bStart = boundaryStartBuf[nCell];
//				uint bCount = boundaryCountBuf[nCell];
//
//				for(uint i = 0u; i < bCount; i++) {
//					uint bIdx = boundarySortedIndexBuf[bStart + i];
//					vec3 Pib = Pi - boundaryGhostPart[bIdx].xyz;
//					float r = length(Pib);
//					if(r >= h || r <= 1e-6) continue;
//
//					float w = boundaryGhostPart[bIdx].w;
//					vec3 gradW = gradW_spiky(Pib, r, h);
//
//					deltaBoundary += (Lambdai * w / restDensity) * gradW;
//
//
//				}
//
//
//			}
//
//
//		}
//
//
//	}

	vec3 delta = (mass / restDensity) * deltaFluid + deltaBoundary;
	deltaPosBuf[idx] = vec4(delta, 0.0);

}