#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer Particles {
	vec4 pos[];
};

layout(std430, binding = 1) buffer Velocities {
	vec4 vel[];
};

layout(std430, binding = 11) buffer PredictedPositions {
	vec4 predictedPos[];
};

uniform vec3 boxMin;
uniform vec3 boxMax;
uniform vec3 gravity;
uniform float particleRadius;
uniform float deltaTime;
uniform float wallDamping;
uniform uint particleCount;


void main() {
	uint idx = gl_GlobalInvocationID.x;
	if(idx >= particleCount) return;

	vec3 p = pos[idx].xyz;
	vec3 v = vel[idx].xyz;

	//external forces
	vec3 a = gravity;
	v += a * deltaTime;
	vec3 predP = p + v * deltaTime;

	vec3 minB = boxMin + vec3(particleRadius);
    vec3 maxB = boxMax - vec3(particleRadius);

	predP = clamp(predP, minB, maxB);
	predictedPos[idx] = vec4(predP, 1.0);

}

