#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer Particles { vec4 pos[]; };
layout(std430, binding = 1) readonly buffer Velocities { vec4 vel[]; };
layout(std430, binding = 2) readonly buffer CellCount { uint countBuf[]; };
layout(std430, binding = 3) readonly buffer CellOffset { uint cellOffsetBuf[]; };
layout(std430, binding = 5) readonly buffer ParticleCell { uint particleCell[]; };
layout(std430, binding = 6) readonly buffer SortedIndex { uint sortedIndexBuf[]; };
layout(std430, binding = 7) readonly buffer ParticleDensities { float densityBuf[]; };
layout(std430, binding = 14) buffer ParticleVorticities  { vec4 vorticityBuf[]; };

uniform uint particleCount;
uniform uint gridResX;
uniform uint gridResY;
uniform uint gridResZ;
uniform float h;
uniform float mass;
uniform float PI;
uniform float restDensity;

uint flatten(uvec3 c) {
	return c.x + gridResX * (c.y + gridResY * c.z);
}

vec3 gradW_spiky(vec3 Rij, float r, float hVal) {
	if(r <= 1e-6 || r >= hVal) return vec3(0.0);
	float coeff = -45.0 / (PI * pow(hVal, 6.0));
	float a = (hVal - r);
	return coeff * a * a * (Rij / r);
}

void main() {
	uint idx = gl_GlobalInvocationID.x;
	if(idx >= particleCount) return;

	vec3 Pi = pos[idx].xyz;
	vec3 Vi = vel[idx].xyz;
	uint cellId = particleCell[idx];
	ivec3 base = ivec3(int(cellId % gridResX), int((cellId / (gridResX) % gridResY)), int(cellId / (gridResX * gridResY)));

	vec3 omega = vec3(0.0);

	for(int dz = -1; dz <= 1; dz++) {
		for(int dy = -1; dy <= 1; dy++) {
			for(int dx = -1; dx <= 1; dx++) {
				ivec3 c = base + ivec3(dx, dy, dz);
				if(c.x < 0 || c.y < 0 || c.z < 0) continue;
				if(c.x >= int(gridResX) || c.y >= int(gridResY) || c.z >= int(gridResZ)) continue;
				uint nCell = flatten(uvec3(c));
				uint start = cellOffsetBuf[nCell];
				uint count = countBuf[nCell];

				for(uint i = 0u; i < count; i++) {
					uint j = sortedIndexBuf[start + i];
					if(j == idx) continue;

					vec3 Pij = Pi - pos[j].xyz;
					float r = length(Pij);
					if(r >= h) continue;

					float Rhoj = max(densityBuf[j], restDensity * 0.1);
					vec3 gradW = gradW_spiky(Pij, r, h);
					omega += (mass / Rhoj) * cross(vel[j].xyz - Vi, gradW);


				}

			}

		}
	}
	vorticityBuf[idx] = vec4(omega, 0.0);

}