#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 1) buffer Velocities { vec4 vel[]; };
layout(std430, binding = 8) readonly buffer ViscosityDelta { vec4 viscosityDelta[]; };

uniform uint particleCount;

void main() {
	uint idx = gl_GlobalInvocationID.x;
	if (idx >= particleCount) return;

	vel[idx] = vec4(vel[idx].xyz + viscosityDelta[idx].xyz, 0.0);
}
