#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 11) readonly buffer PredictedPositions { vec4 predictedPos[]; };
layout(std430, binding = 1) readonly buffer Velocities { vec4 vel[]; };
layout(std430, binding = 2) readonly buffer CellCount { uint countBuf[]; };
layout(std430, binding = 3) readonly buffer CellOffset { uint cellOffsetBuf[]; };
layout(std430, binding = 5) readonly buffer ParticleCell { uint particleCell[]; };
layout(std430, binding = 6) readonly buffer SortedIndex { uint sortedIndexBuf[]; };
layout(std430, binding = 7) readonly buffer ParticleDensities { float densityBuf[]; };
layout(std430, binding = 8) buffer ViscosityDelta { vec4 viscosityDelta[]; };

uniform uint particleCount;
uniform uint gridResX;
uniform uint gridResY;
uniform uint gridResZ;

uniform float h;
uniform float mass;
uniform float PI;
uniform float restDensity;
uniform float viscosityCoeff;

uint flatten(uvec3 c) {
	return c.x + gridResX * (c.y + gridResY * c.z);
}

float W_Poly6(float r, float hVal) {
	if (r >= hVal) return 0.0;
	float hr2 = hVal * hVal - r * r;
	float sigma = 315.0 / (64.0 * PI * pow(hVal, 9.0));
	return sigma * hr2 * hr2 * hr2;
}

void main() {
	uint idx = gl_GlobalInvocationID.x;
	if (idx >= particleCount) return;

	vec3 pi = predictedPos[idx].xyz;
	vec3 vi = vel[idx].xyz;
	uint cellId = particleCell[idx];

	ivec3 base = ivec3(int(cellId % gridResX), int((cellId / gridResX) % gridResY), int(cellId / (gridResX * gridResY)));

	vec3 deltaV = vec3(0.0);

	for (int dz = -1; dz <= 1; dz++) {
		for (int dy = -1; dy <= 1; dy++) {
			for (int dx = -1; dx <= 1; dx++) {
				ivec3 c = base + ivec3(dx, dy, dz);
				if (c.x < 0 || c.y < 0 || c.z < 0) continue;
				if (c.x >= int(gridResX) || c.y >= int(gridResY) || c.z >= int(gridResZ)) continue;

				uint nCell = flatten(uvec3(c));
				uint start = cellOffsetBuf[nCell];
				uint count = countBuf[nCell];

				for (uint i = 0u; i < count; i++) {
					uint j = sortedIndexBuf[start + i];
					if (j == idx) continue;

					vec3 pij = pi - predictedPos[j].xyz;
					float r = length(pij);
					if (r >= h) continue;
					vec3 vj = vel[j].xyz;

					float Rhoj = max(densityBuf[j], restDensity * 0.1);
					deltaV += (mass / Rhoj) * (vj - vi) * W_Poly6(r, h);
				}
			}
		}
	}

	deltaV *= viscosityCoeff;
	viscosityDelta[idx] = vec4(deltaV, 0.0);
}
