#version 430 core

layout (local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

layout(std430, binding = 2) buffer CellCount {
	uint countBuf[];
};

uniform uint gridResX;
uniform uint gridResY;
uniform uint gridResZ;

uint flatten(uvec3 c) {
	return c.x + gridResX * (c.y + gridResY * c.z);
}

void main() {
	uvec3 c = gl_GlobalInvocationID.xyz;
	if(c.x >= gridResX || c.y >= gridResY || c.z >= gridResZ) return;
	countBuf[flatten(c)] = 0u;
}