#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 2) buffer CellCount { uint countBuf[]; };
layout(std430, binding = 3) buffer CellOffset { uint cellOffsetBuf[]; };
layout(std430, binding = 15) buffer BlockSums { uint blockSums[]; };


uniform uint elementCount;

shared uint temp[512];

void main() {
	uint lid = gl_LocalInvocationID.x;
	uint gid = gl_WorkGroupID.x;
	uint base = gid * 512u;

	uint i0 = base + lid;
	uint i1 = base + lid + 256u;

	temp[lid] = (i0 < elementCount) ? countBuf[i0] : 0u;
	temp[lid + 256] = (i1 < elementCount) ? countBuf[i1] : 0u;

	barrier();

	for(uint offset = 1u; offset < 512u; offset *= 2u) {
		uint idx = ((lid + 1u) * offset * 2u) - 1u;
		if(idx < 512u) {
			temp[idx] += temp[idx - offset];
		}
		barrier();
	}

	if(lid == 0u) {
		blockSums[gid] = temp[511];
		temp[511] = 0u;
	}

	barrier();

	for(uint offset = 256u; offset >= 1u; offset /= 2u) {
		uint idx = ((lid + 1u) * offset * 2u) - 1u;
		if(idx < 512u) {
			uint t = temp[idx - offset];
			temp[idx - offset] = temp[idx];
			temp[idx] += t;
		}
		barrier();
		if(offset == 1u) break;
	}

	if(i0 < elementCount) cellOffsetBuf[i0] = temp[lid];
	if(i1 < elementCount) cellOffsetBuf[i1] = temp[lid + 256u];

}