#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer Particles {
	vec4 pos[];
};

layout(std430, binding = 1) buffer Velocities {
	vec4 vel[];
};

uniform vec3 boxMin;
uniform vec3 boxMax;
uniform float particleRadius;
uniform float deltaTime;
uniform float wallDamping;
uniform uint particleCount;

void main() {
	uint idx = gl_GlobalInvocationID.x;
	if(idx >= particleCount) return;

	vec3 v = vel[idx].xyz;
	
	vec3 p = pos[idx].xyz;
	p += v * deltaTime;

	vec3 minB = boxMin + vec3(particleRadius);
    vec3 maxB = boxMax - vec3(particleRadius);
	
    if (p.x < minB.x) { p.x = minB.x; v.x = -v.x * wallDamping; }
    else if (p.x > maxB.x) { p.x = maxB.x; v.x = -v.x * wallDamping; }

    if (p.y < minB.y) { p.y = minB.y; v.y = -v.y * wallDamping; }
    else if (p.y > maxB.y) { p.y = maxB.y; v.y = -v.y * wallDamping; }

    if (p.z < minB.z) { p.z = minB.z; v.z = -v.z * wallDamping; }
    else if (p.z > maxB.z) { p.z = maxB.z; v.z = -v.z * wallDamping; }


	vel[idx] = vec4(v, 0.0);
	pos[idx] = vec4(p, 1.0);

}