#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer Particles {
	vec4 pos[];
};

layout(std430, binding = 1) buffer Velocities {
	vec4 vel[];
};

uniform float deltaTime;
uniform uint particleCount;

void main() {
	uint idx = gl_GlobalInvocationID.x;
	if(idx >= particleCount) return;

	vec3 v = vel[idx].xyz;
	
	vec3 p = pos[idx].xyz;
	p += v * deltaTime;

	vel[idx] = vec4(v, 0.0);
	pos[idx] = vec4(p, 1.0);

}