#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer Particles { vec4 pos[]; };
layout(std430, binding = 2) buffer CellCount { uint countBuf[]; };
layout(std430, binding = 3) buffer CellWrite { uint cellWriteBuf[]; };
layout(std430, binding = 5) buffer ParticleCell { uint particleCell[]; };
layout(std430, binding = 6) buffer SortedIndex { uint sortedIndexBuf[]; };
layout(std430, binding = 7) buffer ParticleDensities { float densityBuf[]; };
layout(std430, binding = 9) buffer ParticlePressure { float pressureBuf[]; };
layout(std430, binding = 10) buffer ParticlePressureAccel { vec4 pressureAccelBuf[]; };
layout(std430, binding = 11) readonly buffer BoundaryCellCount { uint boundaryCountBuf[]; };
layout(std430, binding = 12) readonly buffer BoundaryCellStart { uint boundaryStartBuf[]; };
layout(std430, binding = 13) readonly buffer BoundarySortedIndex { uint boundarySortedIndexBuf[]; };
layout(std430, binding = 15) readonly buffer BoundaryPos { vec4 boundaryGhostPart[]; };

uniform uint particleCount;
uniform uint gridResX;
uniform uint gridResY;
uniform uint gridResZ;
uniform uint boundaryCount;

uniform float h;
uniform float mass;
uniform float PI;
uniform float restDensity;
uniform float stiffness;

uint flatten(uvec3 c) {
	return c.x + gridResX * (c.y + gridResY * c.z);
}

float W_cubic(float r, float hVal) {
	float q = r / hVal;
	if(q >= 1.0) return 0.0;
	float sigma = 8.0 / (PI * hVal * hVal * hVal);

	if(q < 0.5) {
		return sigma * (6.0 * q * q * q - 6.0 * q * q + 1.0);
	}
	else {
		float a = 1.0 - q;
		return sigma * 2.0 * a * a * a;
	}

}

vec3 gradW_spiky(vec3 Rij, float r, float hVal) {
	if(r <= 1e-6 || r >= hVal) return vec3(0.0);
	float coeff = -45.0 / (PI * pow(hVal, 6.0));
	float a = (hVal - r);
	return coeff * a * a * (Rij / r);
}

void main() {
	uint idx = gl_GlobalInvocationID.x;
	if(idx >= particleCount) return;

	vec3 Pi = pos[idx].xyz;
	float Rhoi = max(densityBuf[idx], 1e-6);

	float PiPressure = max(stiffness * (Rhoi - restDensity), 0.0);
	pressureBuf[idx] = PiPressure;

	uint cellId = particleCell[idx];

	ivec3 base = ivec3(int(cellId % gridResX), int((cellId / (gridResX) % gridResY)), int(cellId / (gridResX * gridResY)));

	vec3 pressureAccel = vec3(0.0);

	for(int dz = -1; dz <= 1; dz++) {
		for(int dy = -1; dy <= 1; dy++) {
			for(int dx = -1; dx <= 1; dx++) {
				ivec3 c = base + ivec3(dx, dy, dz);
				if(c.x < 0 || c.y < 0 || c.z < 0) continue;
				if(c.x >= int(gridResX) || c.y >= int(gridResY) || c.z >= int(gridResZ)) continue;

				uint nCell = flatten(c);
				uint start = cellWriteBuf[nCell];
				uint count = countBuf[nCell];

				for(uint i = 0u; i < count; i++) {
					uint j = sortedIndexBuf[start + i];
					if(j == idx) continue;

					vec3 Rij = Pi - pos[j].xyz;
					float r = length(Rij);
					if(r >= h) continue;

					float Rhoj = max(densityBuf[j], 1e-6);
					float Pj = max(stiffness * (Rhoj - restDensity), 0.0);

					vec3 gradW = gradW_spiky(Rij, r, h);
					pressureAccel += -mass * (PiPressure + Pj) / (2.0 * Rhoj) * gradW;



				}


			}

		}



	}
	for(int dz = -1; dz <= 1; dz++) {
		for(int dy = -1; dy <= 1; dy++) {
			for(int dx = -1; dx <= 1; dx++) {
				ivec3 c = base + ivec3(dx, dy, dz);
				if(c.x < 0 || c.y < 0 || c.z < 0) continue;
				if(c.x >= int(gridResX) || c.y >= int(gridResY) || c.z >= int(gridResZ)) continue;

				uint nCell = flatten(c);
				uint bStart = boundaryStartBuf[nCell];
				uint bCount = boundaryCountBuf[nCell];

				for(uint i = 0u; i < bCount; i++) {
					uint bIdx = boundarySortedIndexBuf[bStart + i];
					vec3 Rij = Pi - boundaryGhostPart[bIdx].xyz;
					float r = length(Rij);
					if(r <= 1e-6 || r >= h ) continue;

					float weight = boundaryGhostPart[bIdx].w;
					vec3 gradW = gradW_spiky(Rij, r, h);
					pressureAccel += -PiPressure * weight * gradW / Rhoi;
				}
			}
		}
	}
	vec3 aPressure = pressureAccel / Rhoi;
	pressureAccelBuf[idx] = vec4(aPressure, 0.0);

}